# Generated by Django 4.0 on 2021-12-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='postteacher',
            name='groups',
        ),
        migrations.AddField(
            model_name='groupe',
            name='postteacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.postteacher'),
        ),
    ]
