# Generated by Django 4.0 on 2021-12-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_groupe_teacher_remove_postteacher_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postteacher',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
    ]
