# Generated by Django 4.0 on 2021-12-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_postteacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='pic',
        ),
    ]
