# Generated by Django 4.0 on 2021-12-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images'),
        ),
    ]
