# Generated by Django 4.0 on 2021-12-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='adress',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.level'),
        ),
        migrations.AddField(
            model_name='school',
            name='matier',
            field=models.ManyToManyField(to='Home.Matier'),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='pic',
            field=models.ImageField(blank=True, default='/user.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='wilaya',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.wilaya'),
        ),
    ]
