# Generated by Django 4.0 on 2021-12-30 13:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('school', '0002_school_adress_school_bio_school_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='PostSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('Annee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.annee')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.division')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.level')),
                ('matier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.matier')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
