# Generated by Django 4.0 on 2021-12-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_pic_postschool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postschool',
            old_name='teacher',
            new_name='school',
        ),
    ]
