# Generated by Django 4.0 on 2021-12-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_teacher_postschool_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='pic',
            field=models.ImageField(blank=True, default='school.png', null=True, upload_to='images'),
        ),
    ]
