# Generated by Django 4.0 on 2021-12-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('school', '0005_alter_school_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_groupe', models.IntegerField()),
                ('starttime', models.TimeField()),
                ('endstime', models.TimeField()),
                ('nombredeplace', models.IntegerField(default=None)),
                ('Days', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.days')),
                ('postschool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.postschool')),
            ],
        ),
    ]
