# Generated by Django 4.0 on 2021-12-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pic',
        ),
    ]
