# Generated by Django 4.0 on 2021-12-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images'),
        ),
    ]
